// Style object + static config, extracted verbatim from the original
// monolithic BookEditor. Consider CSS Modules later — kept as JS objects
// here so this refactor is a pure structural change with zero visual diff.
export const s = {
  root: { height: "100vh", display: "flex", flexDirection: "column", fontFamily: "DM Sans, sans-serif", background: "#faf7f2", overflow: "hidden" },
  rootFocus: { background: "#1a1612" },
  header: { height: 56, background: "#1a1612", display: "flex", alignItems: "center", padding: "0 14px", gap: 12, flexShrink: 0 },
  backBtn: { background: "transparent", border: "none", color: "rgba(250,247,242,0.55)", fontSize: 12, cursor: "pointer", fontFamily: "DM Sans,sans-serif", whiteSpace: "nowrap" },
  bookTitleInput: { flex: 1, maxWidth: 320, background: "transparent", border: "none", borderBottom: "1px solid rgba(250,247,242,0.15)", color: "#faf7f2", fontFamily: "Playfair Display,serif", fontSize: 16, padding: "4px 8px", outline: "none", textAlign: "center" },
  headerRight: { display: "flex", alignItems: "center", gap: 5, marginLeft: "auto" },
  saveDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0 },
  tabSwitcher: { display: "flex", background: "rgba(250,247,242,0.08)", borderRadius: 8, padding: 3, gap: 2 },
  tabBtn: { background: "transparent", border: "none", color: "rgba(250,247,242,0.5)", padding: "4px 9px", borderRadius: 6, fontSize: 11, fontWeight: 500, cursor: "pointer", fontFamily: "DM Sans,sans-serif", display: "flex", alignItems: "center", gap: 3, whiteSpace: "nowrap" },
  tabBtnActive: { background: "rgba(250,247,242,0.15)", color: "#faf7f2" },
  hBtn: { background: "transparent", border: "1px solid rgba(250,247,242,0.2)", color: "#faf7f2", padding: "5px 9px", borderRadius: 6, fontSize: 11, cursor: "pointer", fontFamily: "DM Sans,sans-serif", fontWeight: 500, whiteSpace: "nowrap" },
  focusBar: { background: "#1a1612", height: 42, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 24px", flexShrink: 0, borderBottom: "1px solid rgba(250,247,242,0.08)" },
  focusInfo: { display: "flex", alignItems: "center", gap: 14 },
  focusTitle: { fontFamily: "Playfair Display,serif", color: "rgba(250,247,242,0.45)", fontSize: 14 },
  focusWords: { fontSize: 12, color: "rgba(250,247,242,0.3)" },
  focusControls: { display: "flex", gap: 8 },
  focusToggle: { background: "transparent", border: "1px solid rgba(250,247,242,0.15)", color: "rgba(250,247,242,0.5)", padding: "4px 10px", borderRadius: 6, fontSize: 11, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  exitFocusBtn: { background: "transparent", border: "none", color: "rgba(250,247,242,0.4)", fontSize: 12, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  workspace: { flex: 1, display: "flex", overflow: "hidden" },
  sidebar: { width: 228, background: "#3d342b", display: "flex", flexDirection: "column", flexShrink: 0 },
  sideTop: { padding: "10px 10px 7px", borderBottom: "1px solid rgba(250,247,242,0.08)", display: "flex", justifyContent: "space-between", alignItems: "center" },
  sideLabel: { fontSize: 9, fontWeight: 700, color: "rgba(250,247,242,0.3)", letterSpacing: "1.2px", textTransform: "uppercase" },
  addChBtn: { background: "transparent", border: "1px dashed rgba(250,247,242,0.2)", color: "rgba(250,247,242,0.4)", padding: "2px 7px", borderRadius: 5, fontSize: 10, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  sideScroll: { flex: 1, overflowY: "auto", padding: "6px 5px" },
  chRow: { display: "flex", alignItems: "center", gap: 3, padding: "5px 6px", borderRadius: 6, cursor: "pointer", color: "rgba(250,247,242,0.65)" },
  chRowActive: { background: "rgba(212,134,10,0.15)", color: "#f5d98a" },
  chChevron: { fontSize: 10, width: 12, flexShrink: 0 },
  chName: { flex: 1, fontSize: 12, fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  chBtn: { background: "transparent", border: "none", color: "rgba(250,247,242,0.25)", fontSize: 10, cursor: "pointer", padding: "1px 2px" },
  pagesList: { marginLeft: 16, marginBottom: 2 },
  pageRow: { display: "flex", alignItems: "center", gap: 5, padding: "4px 7px", borderRadius: 5, cursor: "pointer", color: "rgba(250,247,242,0.4)", fontSize: 11 },
  pageRowActive: { color: "#f5d98a", background: "rgba(212,134,10,0.1)" },
  pageDot: { width: 3, height: 3, borderRadius: "50%", background: "currentColor", flexShrink: 0 },
  pageName: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  pageWords: { fontSize: 9, color: "rgba(250,247,242,0.2)" },
  addPageBtn: { background: "transparent", border: "none", color: "rgba(250,247,242,0.2)", fontSize: 10, cursor: "pointer", padding: "3px 7px", fontFamily: "DM Sans,sans-serif" },
  sideStats: { padding: "10px", borderTop: "1px solid rgba(250,247,242,0.08)" },
  statsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 5 },
  statBox: { background: "rgba(250,247,242,0.05)", borderRadius: 6, padding: "6px 8px" },
  statVal: { fontFamily: "Playfair Display,serif", fontSize: 16, fontWeight: 700, color: "#faf7f2" },
  statLbl: { fontSize: 9, color: "rgba(250,247,242,0.3)" },
  mainArea: { flex: 1, display: "flex", overflow: "hidden" },
  tabContent: { flex: 1, overflowY: "auto", background: "#faf7f2" },
  editorArea: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  toolbar: { padding: "6px 12px", borderBottom: "1px solid #e0d8ca", background: "#f0ebe0", display: "flex", alignItems: "center", gap: 2, flexShrink: 0, flexWrap: "wrap" },
  tbtn: { background: "transparent", border: "none", padding: "4px 7px", borderRadius: 4, cursor: "pointer", fontSize: 13, color: "#7a6e62", fontFamily: "DM Sans,sans-serif", minWidth: 24 },
  tbtnActive: { background: "#fdf3dc", color: "#d4860a" },
  sep: { width: 1, height: 16, background: "#e0d8ca", margin: "0 2px" },
  editorScroll: { flex: 1, overflowY: "auto", padding: "28px 0", background: "#faf7f2" },
  editorScrollFocus: { background: "#1a1612", padding: "60px 0" },
  paper: { maxWidth: 700, margin: "0 auto", padding: "44px 56px", background: "#fff", borderRadius: 12, boxShadow: "0 4px 24px rgba(26,22,18,0.1)", minHeight: 800 },
  paperFocus: { background: "#1e1916", boxShadow: "none", borderRadius: 0, minHeight: "80vh", maxWidth: 680 },
  pageHeading: { fontSize: 10, fontWeight: 600, color: "#c0b5a8", letterSpacing: "1px", textTransform: "uppercase", marginBottom: 22 },
  editor: { minHeight: 680, outline: "none", fontFamily: "Playfair Display,serif", fontSize: 17, lineHeight: 1.9, color: "#1a1612", caretColor: "#d4860a" },
  editorFocus: { color: "#f0ebe0", caretColor: "#f5d98a", fontSize: 19, lineHeight: 2.05 },
  statusBar: { padding: "6px 14px", borderTop: "1px solid #e0d8ca", background: "#f0ebe0", display: "flex", gap: 14, fontSize: 11, color: "#7a6e62", flexShrink: 0, alignItems: "center", flexWrap: "wrap" },
  exitFocusSmall: { background: "transparent", border: "1px solid #e0d8ca", color: "#7a6e62", padding: "2px 7px", borderRadius: 5, fontSize: 10, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  aiPanel: { width: 288, background: "#f0ebe0", borderLeft: "1px solid #e0d8ca", display: "flex", flexDirection: "column", flexShrink: 0, overflow: "hidden" },
  panelTabs: { display: "flex", borderBottom: "1px solid #e0d8ca", flexShrink: 0 },
  panelTab: { flex: 1, background: "transparent", border: "none", padding: "8px 4px", fontSize: 11, fontWeight: 500, cursor: "pointer", fontFamily: "DM Sans,sans-serif", color: "#7a6e62" },
  panelTabActive: { background: "#fff", color: "#1a1612", borderBottom: "2px solid #d4860a" },
  aiHeader: { padding: "10px 12px", borderBottom: "1px solid #e0d8ca", display: "flex", alignItems: "center", gap: 9 },
  aiOrb: { width: 26, height: 26, borderRadius: "50%", background: "#1a1612", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  aiOrbInner: { width: 10, height: 10, borderRadius: "50%", background: "#f5d98a" },
  aiTitle: { fontSize: 12, fontWeight: 600, color: "#1a1612" },
  aiSub: { fontSize: 10, color: "#7a6e62" },
  aiTools: { padding: "7px", borderBottom: "1px solid #e0d8ca", display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 4 },
  aiToolBtn: { background: "#fff", border: "1px solid #e0d8ca", borderRadius: 7, padding: "6px 4px", cursor: "pointer", fontFamily: "DM Sans,sans-serif", display: "flex", flexDirection: "column", alignItems: "center", fontSize: 15 },
  subMenu: { padding: "7px 8px", borderBottom: "1px solid #e0d8ca", display: "flex", flexWrap: "wrap", gap: 4 },
  subMenuTitle: { width: "100%", fontSize: 9, fontWeight: 700, color: "#7a6e62", letterSpacing: "0.5px", textTransform: "uppercase", marginBottom: 3 },
  subMenuBtn: { background: "#fff", border: "1px solid #e0d8ca", borderRadius: 6, padding: "4px 9px", fontSize: 11, cursor: "pointer", fontFamily: "DM Sans,sans-serif", color: "#3d342b" },
  aiOutput: { flex: 1, overflowY: "auto", padding: "9px", display: "flex", flexDirection: "column", gap: 7 },
  welcomeBubble: { background: "#fdf3dc", border: "1px solid #f5d98a", borderRadius: 10, padding: "11px 12px" },
  bubble: { background: "#fff", border: "1px solid #e0d8ca", borderRadius: 10, padding: "10px 11px" },
  bLabel: { fontSize: 9, fontWeight: 700, color: "#7a6e62", letterSpacing: "0.5px", textTransform: "uppercase", marginBottom: 5 },
  bText: { fontSize: 12, lineHeight: 1.6, color: "#3d342b", whiteSpace: "pre-wrap" },
  bActions: { display: "flex", gap: 5, marginTop: 8 },
  applyBtn: { flex: 1, padding: "5px 7px", background: "#0f6e56", color: "#fff", border: "none", borderRadius: 6, fontSize: 11, fontWeight: 600, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  discardBtn: { padding: "5px 9px", background: "#e0d8ca", color: "#7a6e62", border: "none", borderRadius: 6, fontSize: 11, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  aiInputRow: { padding: "8px", borderTop: "1px solid #e0d8ca", display: "flex", gap: 5 },
  aiInput: { flex: 1, background: "#fff", border: "1px solid #e0d8ca", borderRadius: 7, padding: "6px 9px", fontFamily: "DM Sans,sans-serif", fontSize: 12, color: "#1a1612", outline: "none", resize: "none" },
  sendBtn: { background: "#1a1612", color: "#faf7f2", border: "none", borderRadius: 7, padding: "6px 10px", cursor: "pointer", fontSize: 13 },
  overlay: { position: "fixed", inset: 0, background: "rgba(26,22,18,0.55)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000, padding: 20 },
  modal: { background: "#faf7f2", borderRadius: 14, padding: "24px", width: "100%", maxWidth: 440 },
  modalTitle: { fontFamily: "Playfair Display,serif", fontSize: 20, fontWeight: 700, color: "#1a1612", marginBottom: 14 },
  modalInput: { width: "100%", padding: "9px 12px", border: "1px solid #e0d8ca", borderRadius: 8, fontFamily: "DM Sans,sans-serif", fontSize: 14, color: "#1a1612", background: "#fff", outline: "none", marginBottom: 14 },
  modalActions: { display: "flex", gap: 8, justifyContent: "flex-end" },
  exportOpt: { border: "1px solid #e0d8ca", borderRadius: 8, padding: "14px 8px", textAlign: "center", cursor: "pointer", background: "#fff" },
  cancelBtn: { background: "transparent", border: "1px solid #e0d8ca", color: "#7a6e62", padding: "7px 14px", borderRadius: 7, fontSize: 13, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  primaryBtn: { background: "#1a1612", color: "#faf7f2", border: "none", padding: "7px 16px", borderRadius: 7, fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
};

export const TABS = [
  { id: "write", icon: "✍️", label: "Write" },
  { id: "characters", icon: "🎭", label: "Cast" },
  { id: "plot", icon: "🗂️", label: "Plot" },
  { id: "analytics", icon: "📊", label: "Stats" },
];

export const AI_TOOLS = [
  ["✨", "Fix Grammar", "fix-grammar"],
  ["♻", "Rewrite", "rewrite"],
  ["➕", "Continue", "continue"],
  ["📋", "Summarize", "summarize"],
  ["🔭", "Expand", "expand"],
  ["🔍", "Simplify", "simplify"],
  ["🎭", "Tone", "tone-menu"],
  ["💡", "Ideas", "writers-block"],
];

export const TONES = ["professional", "casual", "emotional", "academic", "storytelling"];

export const WRITERS_BLOCK_TYPES = [
  { id: "continuation", label: "Continue story" },
  { id: "plot", label: "Plot ideas" },
  { id: "character", label: "Character ideas" },
  { id: "scene", label: "Scene ideas" },
];

export const AI_CONFIG = (extra) => ({
  "fix-grammar": { label: "✨ Grammar Fix", canApply: true, mode: "replace", apiKey: "fixGrammar" },
  rewrite: { label: "♻ Rewrite", canApply: true, mode: "replace", apiKey: "rewrite" },
  continue: { label: "➕ Continue", canApply: true, mode: "append", apiKey: "continueWriting" },
  summarize: { label: "📋 Summary", canApply: false, apiKey: "summarize" },
  expand: { label: "🔭 Expand", canApply: true, mode: "replace", apiKey: "expand" },
  simplify: { label: "🔍 Simplify", canApply: true, mode: "replace", apiKey: "simplify" },
  tone: { label: `🎭 Tone: ${extra.tone || ""}`, canApply: true, mode: "replace", apiKey: "tone" },
  "writers-block": { label: "💡 Ideas", canApply: false, apiKey: "writersBlock" },
});

export const PAGE_WORD_LIMIT = 350;
export const PAGE_CHAR_LIMIT = 2500;
